name = "preferans"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Set ADMIN_EMAIL in Cloudflare Pages environment variables to identify the user
# who can manage the allowlist.

[[d1_databases]]
binding = "DB"
database_name = "preferans-db"
database_id = "f0459e96-4a30-451a-a093-8b373ae0adf3"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"
script_name = "preferans"
